AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-python3.8

Globals:
  Function:
    Timeout: 3

Resources:
  FiapPagamentoMsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        FiapPagamentoMs:
          Type: Api 
          Properties:
            Path: /hello
            Method: post

Outputs:
  FiapPagamentoMsApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  FiapPagamentoMsFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt FiapPagamentoMsFunction.Arn
  FiapPagamentoMsFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt FiapPagamentoMsFunctionRole.Arn
